"""m3 preference system

Revision ID: 28d8c85cf1a4
Revises: 59c4bee34177
Create Date: 2025-12-15 09:45:33.306298

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "28d8c85cf1a4"
down_revision: Union[str, None] = "59c4bee34177"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_preference_stats",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("positive_count", sa.Float(), nullable=False),
        sa.Column("negative_count", sa.Float(), nullable=False),
        sa.Column("source_affinity", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("author_affinity", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.add_column(
        "entries",
        sa.Column(
            "embedding_status",
            sa.String(length=20),
            nullable=False,
            server_default="pending",
        ),
    )
    op.add_column("entries", sa.Column("embedding_error", sa.Text(), nullable=True))
    op.add_column("entries", sa.Column("embedding_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("entries", sa.Column("word_count", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_entries_embedding_status"), "entries", ["embedding_status"], unique=False
    )
    op.drop_column("user_entries", "preference_score")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_entries",
        sa.Column(
            "preference_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix_entries_embedding_status"), table_name="entries")
    op.drop_column("entries", "word_count")
    op.drop_column("entries", "embedding_at")
    op.drop_column("entries", "embedding_error")
    op.drop_column("entries", "embedding_status")
    op.drop_table("user_preference_stats")
    # ### end Alembic commands ###
